## Install dependencies role tasks ##

---

# 1. Install Certbot - Nginx - Docker and their dependencies #

- name: Install dependencies packages
  apt:
    update_cache: yes
    state: latest
    name:
    - apt-transport-https
    - ca-certificates
    - software-properties-common
    - curl
    - gnupg
    - python3-pip
    - libffi-dev
    - python3-dev
    - nginx
    - certbot
    - python3-certbot-nginx
  become: true

##################################################################

# 2. Install Docker #

- name: Add Docker GPG apt Key
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg && chmod a+r /etc/apt/keyrings/docker.gpg
  become: true

- name: Add Docker repository
  shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  become: true

- name: Install docker-ce
  apt:
    update_cache: yes
    name: docker-ce
    state: present
  become: true

- name: Run and enable docker
  service:
    name: docker
    state: started
    enabled: true
  become: true

- name: Add user to Docker group
  user:
    name: "{{ user }}"
    groups: docker
    append: yes
  become: true

##################################################################

# 3. Install Docker Compose #

- name: Install Docker Compose Plugin
  apt:
    name: docker-compose-plugin
    state: present
  become: true

##################################################################
