## Harden server role variables ##
########################################################
ssh_port: $ssh_port
########################################################
ssh_user: "$server_user"
########################################################
ssh_public_key: "$ssh_public_key
########################################################
