## Harden server role variables ##
########################################################
ssh_port: $port
########################################################
ssh_user: "user"
########################################################
ssh_public_key: "$ssh_public_key"
########################################################
