## Install dependencies role tasks ##

---

# 1. Install Certbot - Nginx - Docker and their dependencies #

- name: Install dependencies packages
  apt:
    update_cache: yes
    state: latest
    name:
    - apt-transport-https
    - ca-certificates
    - software-properties-common
    - python3-pip
    - docker.io
    - nginx
    - certbot
    - python3-certbot-nginx
  become: true

- name: Install Docker SDK for Python
  pip:
    name: docker

- script: /usr/sbin/usermod -aG docker {{ docker_access_user }}
  become: true

##################################################################

# 2. Install Docker Compose #

- name: Install Docker Compose
  shell: curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  become: true

- name: Set permission for Docker Compose
  shell: chmod +x /usr/local/bin/docker-compose
  become: true

##################################################################
