## All variables for our roles ##
---
########################################################
ssh_port: "$port"
########################################################
user: "$user"
########################################################
password: "$password"
########################################################
ssh_public_key: "$your_ssh_key"
########################################################
gitlab_runner_registration_token: "$gitlab_runner_registration_token"
########################################################
gitlab_runner_url: "$gitlab_url"
########################################################
gitlab_runner_executor: "shell"
########################################################
