## Gitlab Runner role variables ##
########################################################
gitlab_runner_registration_token: "$registry_token"
########################################################
gitlab_runner_name: "$gitlab_runner_name"
########################################################
gitlab_runner_url: "$gitlab_runner_url"
########################################################
########################################################
gitlab_runner_executor: "shell"
########################################################
gitlab_runner_tags: "$tag"
########################################################
