## User config role variables ##
########################################################
username: "ansible"
########################################################
password: "123456789"
########################################################
