## User config role variables ##
########################################################
username: "$server_user"
########################################################
password: "$server_password"
########################################################
