## User config role variables ##
########################################################
username: "$username"
########################################################
password: "$password"
########################################################
